### PR TITLE
Fixes #30 bot not working with Facebook messenger

### LINKED ISSUE #30: Bot does not operate with Facebook messenger
## Expected Behavior
After publishing the bot as a Facebook messenger bot, I should receive replies for queries that result in matches.

## Actual Behavior
No reply received in messenger. Looking at the CloudWatch logs for the handler reveals the following error:
```
2017-12-01T00:10:49.253Z	159d39bc-d62c-11e7-aca4-39e3bde501a4	TypeError: Cannot convert undefined or null to object
at Object.exports.success (/var/task/lib/response.js:197:19)
at es.ping.tap.then.then.msg (/var/task/index.js:42:39)
at tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/var/task/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/var/task/node_modules/bluebird/js/release/promise.js:693:18)
at Async._drainQueue (/var/task/node_modules/bluebird/js/release/async.js:133:16)
at Async._drainQueues (/var/task/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/var/task/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5)
```

This error is because when using a Lex bot as a Facebook messenger bot, params.Session is not set (i.e. null) per http://docs.aws.amazon.com/lex/latest/dg/ex1-sch-appt-info-flow-details.html

## Steps to Reproduce the Problem

  1. Deploy the bot as a Facebook messenger bot per http://docs.aws.amazon.com/lex/latest/dg/fb-bot-association.html
  2. Send a query that matches one of the questions.

### PR DESCRIPTION
**Pull request by matthewberryman**

### CODE REVIEW

**Comment by matthewberryman** [comment]
I'm not sure the additional work in 8eef6af is all that elegant but it works

**Comment by matthewberryman** [comment]
hold fire - I had 8eef6af work for me once but not repeatedly. Working on a different fix now.

**Comment by matthewberryman** [comment]
Ok the problem was that Session is sometimes !null for Facebook (so a bit of an update on what I wrote in #30). For Lex use I also pass the 'x-amz-lex:channel-type' through as Channel, which acts as a more elegant check that's also now specific to Facebook (in case other solutions for writing in links are required for other platforms) and with 15003f3 this now works every time for me.

**Comment by JohnCalhoun** [comment]
Mathewberryman,
this looks great. i am sending it through our review process.
thank you so much for the contribution!

**Comment by matthewberryman** [comment]
8fcf301 fixes a case where the requestAttributes aren't set, something I noticed now that I have the bot working as a Twitter DM bot (code for that over in https://github.com/MSFREACH/msf-reach-chatbot ), although looking like there in a commit I will soon make that I will need to define my own one to flag it as Twitter DM so that I can pick that up for sending links back.

**Comment by JohnCalhoun** [comment]
matthewberryman,
Please confirm that we can use, modify, copy, and redistribute this contribution. Thanks.

**Comment by matthewberryman** [comment]
Confirmed — yes you can use, modify, copy and redistribute.


On 9 Dec 2017, at 07:35, John M Calhoun wrote:


matthewberryman,
Please confirm that we can use, modify, copy, and redistribute this contribution. Thanks.

**Pull request merged**
